const AppData = [
  {
    id: 1,
    name: 'First React App - Book Store',
    info: 'This app implements react classes, functions, and states.',
    level: 'basic',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c7f03046fcb0000764753d/screenshot_2021-06-15-00-12-02-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/01-first-react-app-bookstore-classes',
    netlify_url: 'https://01-first-react-app-bookstore-classes.netlify.app',
    teqs: ['react', 'classes', 'functions', 'states'],
  },
  {
    id: 2,
    name: 'Book Store - Cart',
    info: 'This app implements react classes, functions, and states.',
    level: 'basic',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c4e6efc55421000739c5e0/screenshot_2021-06-12-16-55-32-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/02-bookstore-cart-usestate',
    netlify_url: 'https://02-bookstore-cart-usestate.netlify.app',
    teqs: ['react', 'classes', 'functions', 'states'],
  },
  {
    id: 3,
    name: 'Book Store - Card',
    info: 'This app implements react hooks, useState and useEffect.',
    level: 'basic',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c4f00be530a700088cfe00/screenshot_2021-06-12-17-34-36-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/03-bookstore-card-usestate',
    netlify_url: 'https://03-bookstore-card-usestate.netlify.app',
    teqs: ['react', 'hooks', 'useState', 'useEffect'],
  },
  {
    id: 4,
    name: 'Book Store - Reviews',
    info: 'This app implements react hooks, and react icons.',
    level: 'basic',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c4f8ffecfc7e1d2a2878bd/screenshot_2021-06-12-18-13-01-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/04-bookstore-reviews-useeffect',
    netlify_url: 'https://04-bookstore-reviews-useeffect.netlify.app',
    teqs: ['react', 'react-hooks', 'react-icons'],
  },
  {
    id: 5,
    name: 'Common Questions',
    info: 'This app implements react hooks, and react icons.',
    level: 'basic',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c693bfebfb71d091046cd5/screenshot_2021-06-13-23-25-44-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/05-common-questions-useeffect',
    netlify_url: 'https://05-common-questions-useeffect.netlify.app',
    teqs: ['react', 'react-hooks', 'react-icons'],
  },
  {
    id: 6,
    name: 'Book Store - Authors Menu',
    info: 'This app implements react hooks.',
    level: 'basic',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c6963f92333d0007686e4c/screenshot_2021-06-13-23-36-17-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/06-bookstore-authormenus-usestate',
    netlify_url: 'https://06-bookstore-authormenus-usestate.netlify.app',
    teqs: ['react', 'react-hooks', 'useState'],
  },
  {
    id: 7,
    name: 'Book Store - Books Menu',
    info: 'This app implements react hooks.',
    level: 'basic',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c698f0588b4c2428e8ff65/screenshot_2021-06-13-23-48-19-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/07-bookstore-booksmenus-usestate',
    netlify_url: 'https://07-bookstore-booksmenus-usestate.netlify.app',
    teqs: ['react', 'react-hooks', 'useState'],
  },
  {
    id: 8,
    name: 'Book Store - Book Reviews',
    info: 'This app implements react hooks, and react icons.',
    level: 'basic',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c699f80fdc7e4788313c32/screenshot_2021-06-13-23-52-13-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/08-bookstore-bookreviews-usestate',
    netlify_url: 'https://08-bookstore-bookreviews-usestate.netlify.app',
    teqs: ['react', 'react-hooks', 'react-icons'],
  },
  {
    id: 9,
    name: 'Lorem Ipsum Generator',
    info: 'This app implements react hooks to generate a dumy text in any number of letters and paragraphs',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c69ae1e4bb6d62e84778a6/screenshot_2021-06-13-23-56-06-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/09-loremipsum-generator-reactforms',
    netlify_url: 'https://09-loremipsum-generator-reactforms.netlify.app',
    teqs: ['react', 'react-hooks', 'forms'],
  },
  {
    id: 10,
    name: 'Color Generator',
    info: 'This app implements react hooks and values.js to generate colors.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c69bf5ceffa8c1f093be4f/screenshot_2021-06-14-00-00-50-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/10-color-generator-reactforms',
    netlify_url: 'https://10-color-generator-reactforms.netlify.app',
    teqs: ['react', 'react-hooks', 'forms', 'valuejs'],
  },
  {
    id: 11,
    name: 'Grocery Bud - useState',
    info: 'This app implements react hooks, react icons, forms and local storage.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c69cbfad233def1e0a05d4/screenshot_2021-06-14-00-04-11-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/11-grocery-bud-reactforms-usestate',
    netlify_url: 'https://11-grocery-bud-reactforms-usestate.netlify.app',
    teqs: ['react', 'react-hooks', 'forms', 'react-icons', 'local-storage'],
  },
  {
    id: 12,
    name: 'Grocery Bud - useReducer',
    info: 'This app implements react hooks and useReducer hook, react icons, forms and local storage.',
    level: 'advanced',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c69d56ad233dfc5a0a0331/screenshot_2021-06-14-00-06-46-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/12-grocery-bud-reactforms-usereducer',
    netlify_url: 'https://12-grocery-bud-reactforms-usereducer.netlify.app',
    teqs: [
      'react',
      'react-hooks',
      'useReducer',
      'forms',
      'react-icons',
      'local-storage',
    ],
  },
  {
    id: 13,
    name: 'Navbar',
    info: 'This app implements react hooks and useRef hook, and react icons.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c69ea2a63c5100079ef3c4/screenshot_2021-06-14-00-12-50-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/13-navbar-useref/tree/main/src',
    netlify_url: 'https://13-navbar-useref.netlify.app',
    teqs: ['react', 'react-hooks', 'useRef', 'react-icons'],
  },
  {
    id: 14,
    name: 'Modal and Sidebar',
    info: 'This app implements react hooks and useContext hook, custom hooks, and react icons.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c69f73e8a42bafbb136f2b/screenshot_2021-06-14-00-15-46-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/14-modal-sidebar-usecontext',
    netlify_url: 'https://14-modal-sidebar-usecontext.netlify.app',
    teqs: ['react', 'react-hooks', 'useContext', 'custom-hooks', 'react-icons'],
  },
  {
    id: 15,
    name: 'Sub Menus',
    info: 'This app implements react hooks, custom hooks, and react icons.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c6a02eea604d1cdf5d7f19/screenshot_2021-06-14-00-18-47-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/15-stripe-submenus-usecontext',
    netlify_url: 'https://15-stripe-submenus-usecontext.netlify.app',
    teqs: ['react', 'react-hooks', 'custom-hooks', 'react-icons'],
  },
  {
    id: 16,
    name: 'Cart',
    info: 'This app implements react hooks, useContext, and useReducer, and custom hooks.',
    level: 'advanced',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c6a0e1ea604d1d7c5d7e64/screenshot_2021-06-14-00-21-43-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/16-cart-usereducer-usecontext',
    netlify_url: 'https://16-cart-usereducer-usecontext.netlify.app',
    teqs: ['react', 'react-hooks', 'useContext', 'useReducer', 'custom-hooks'],
  },
  {
    id: 17,
    name: 'Cocktails',
    info: 'This app searchs for non alcoholic cocktails within thecocktaildb api and renders a detailed page for each cocktail using react hooks and react router dom.',
    level: 'advanced',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c6b6ebe5b86500074e3a8e/screenshot_2021-06-14-01-55-15-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/17-cocktails-router-usecallback',
    netlify_url: 'https://17-cocktails-router-usecallback.netlify.app',
    teqs: ['react', 'react-hooks', 'react-router-dom', 'thecocktaildb-api'],
  },
  {
    id: 18,
    name: 'Book Store - Book Details',
    info: 'This app implements react classes, sass and fontawesome library.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60c979403277e00007a6acec/screenshot_2021-06-16-04-09-38-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/18-bookstore-details-classes',
    netlify_url: 'https://18-bookstore-details-classes.netlify.app',
    teqs: ['react', 'react-classes', 'sass', 'fontawesome'],
  },
  {
    id: 19,
    name: 'Todo List',
    info: 'This app implements react classes, bootstrap framework, uuid tool, and fontawesome library.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60cbb4318827670008721d33/screenshot_2021-06-17-20-46-03-0000.png',
    github_url: 'https://github.com/Ahmed-AlSharkawy/19-todolist-react-classes',
    netlify_url: 'https://19-todolist-react-classes.netlify.app',
    teqs: ['react', 'react-classes', 'bootstrap', 'uuid', 'fontawesome'],
  },
  {
    id: 20,
    name: 'Hotel Rooms',
    info: 'This app renders rooms list and a detailed page for each room, and provides rooms filter and rooms sort functionalty. It uses contentful, react classes, icons, router, prop types and styled components.',
    level: 'large',
    img: 'https://d33wubrfki0l68.cloudfront.net/60d51250c86a9e000726bd1c/screenshot_2021-06-24-23-17-48-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/20-hotelresort-classes-router',
    netlify_url: 'https://20-hotelresort-classes-router.netlify.app',
    teqs: [
      'react',
      'react-classes',
      'prop-types',
      'react-icons',
      'react-router-dom',
      'styled-components',
      'contentful',
    ],
  },
  {
    id: 21,
    name: 'Tech Store',
    info: 'Complete app that provie products listing, paginating, filtering functionality, and complete login/signup, cart, payment system. it uses herouk, strapi, cloudinary, for backend api, stripe for payment process, and react hooks, icons, router, prop types and styled components in the frontend.',
    level: 'large',
    img: 'https://d33wubrfki0l68.cloudfront.net/60ee84ed2724e9fc32dd850d/screenshot_2021-07-14-06-32-42-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/tech-store-react-strapi-api',
    netlify_url: 'https://tech-store-react-strapi-heroku.netlify.app',
    teqs: [
      'react',
      'react-hooks',
      'prop-types',
      'react-icons',
      'react-router-dom',
      'heroku',
      'strapi',
      'cloudinary',
      'stripe',
    ],
  },
  {
    id: 22,
    name: 'Markdown Preview',
    info: 'This app implements react hooks and remark.js.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60ee8439b755bd0407238581/screenshot_2021-07-14-06-30-27-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/22-markdown-preview-react-hooks',
    netlify_url: 'https://22-markdown-preview-react-hooks.netlify.app',
    teqs: ['react', 'react-hooks', 'remarkjs'],
  },
  {
    id: 23,
    name: 'Random Person',
    info: 'This app implements react hooks, react icons, and random user api.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/60fa8f19afa977a4369df7cb/screenshot_2021-07-23-09-43-52-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/23-random-person-react-hooks',
    netlify_url: 'https://random-person-react-hooks.netlify.app',
    teqs: ['react', 'react-hooks', 'reat-icons', 'random-user'],
  },
  {
    id: 24,
    name: 'Github Users Pagination',
    info: 'This app implements client side pagination and server side pagination in showing github users followers, followings, and repositories using react hooks, react router dom and github api.',
    level: 'large',
    img: 'https://d33wubrfki0l68.cloudfront.net/610809f38fa4bd0008633e18/screenshot_2021-08-02-15-06-51-0000.png',
    github_url: 'https://github.com/Ahmed-AlSharkawy/24-pagination-react-hooks',
    netlify_url:
      'https://app.netlify.com/sites/unsplash-infinit-scroll-react-hooks',
    teqs: ['react', 'react-hooks', 'reat-router-dom', 'github-api'],
  },
  {
    id: 25,
    name: 'Infinit Scroll',
    info: 'This app implements infinit scrolling functionality and search functionality using react hooks, react icons and unsplash api.',
    level: 'advanced',
    img: 'https://d33wubrfki0l68.cloudfront.net/61294bbd931c4800074045b4/screenshot_2021-08-27-20-32-27-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/25-unsplash-infinit-scroll-react-hooks',
    netlify_url: 'https://unsplash-infinit-scroll-react-hooks.netlify.app',
    teqs: ['react', 'react-hooks', 'reat-icons', 'unsplash'],
  },
  {
    id: 26,
    name: 'Dark Mode',
    info: 'This app implements dark mode functionality and date/ time formatting using react hooks and moment.js.',
    level: 'intermediate',
    img: 'https://d33wubrfki0l68.cloudfront.net/61092d64e990eef2677a58a0/screenshot_2021-08-03-11-50-57-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/26-dark-mode-moment-react-hooks',
    netlify_url: 'https://dark-mode-moment-react-hooks.netlify.app',
    teqs: ['react', 'react-hooks', 'momentjs'],
  },
  {
    id: 27,
    name: 'Hacker News',
    info: 'This app implements search and pagination functionality using react hooks and algolia api.',
    level: 'advanced',
    img: 'https://d33wubrfki0l68.cloudfront.net/6113ac49aa8480bb6603db38/screenshot_2021-08-11-10-54-58-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/28-hacker-news-algolia-api-react-hooks',
    netlify_url: 'https://hacker-news-algolia-api-react-hooks.netlify.app',
    teqs: ['react', 'react-hooks', 'algolia'],
  },
  {
    id: 28,
    name: 'Quiz App',
    info: 'This app renders questions and answers responsing to user specifications and calculates the results. It uses react hooks and opentdb api.',
    level: 'advanced',
    img: 'https://d33wubrfki0l68.cloudfront.net/6120ab6d16ea33839c13c4bd/screenshot_2021-08-21-07-31-08-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/29-quiz-opentdb-react-hooks',
    netlify_url: 'https://quiz-opentdb-react-hooks.netlify.app',
    teqs: ['react', 'react-hooks', 'opentdb'],
  },
  {
    id: 29,
    name: 'Github Users Charts',
    info: 'This app renders github users info, followers, and charts about their repositories, and uses login system so that only registered users can use the site. It uses fusioncharts for the charts, auth0 for login system, and react hooks,react icons, react router dom, and styled components.',
    level: 'large',
    img: 'https://d33wubrfki0l68.cloudfront.net/612e06ca7895fb00083a9ea0/screenshot_2021-08-31-10-40-36-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/30-githubusers-fusioncharts-auth0-react',
    netlify_url: 'https://githubusers-fusioncharts-auth0-react.netlify.app',
    teqs: [
      'react',
      'react-hooks',
      'react-icons',
      'react-router-dom',
      'styled-components',
      'fusion-charts',
      'auth0',
    ],
  },
  {
    id: 30,
    name: 'Comfy Sloth Storehouse',
    info: 'This is an e-commerce application which using react framework along with react icons library, styled components, and react router dom. It is also using formspree tool for receiving emails from users, auth0 for managing authentications and login processes, stripe for payment functionality, axios for posting to the server, and netlify cli functions to communicate with stripe. The app was created within vscode environment and git and github tools, and was deployed to netlify service.',
    level: 'large',
    img: 'https://d33wubrfki0l68.cloudfront.net/6142946ad90d663f67da0257/screenshot_2021-09-16-00-51-36-0000.png',
    github_url:
      'https://github.com/Ahmed-AlSharkawy/31-comfy-sloth-react-auth0-stripe',
    netlify_url: 'https://comfy-sloth-react-auth0-stripe.netlify.app',
    teqs: [
      'react',
      'react-hooks',
      'react-icons',
      'react-router-dom',
      'styled-components',
      'vscode',
      'git',
      'github',
      'netlify',
      'formspree',
      'auth0',
      'stripe',
      'axios',
      'netlify-cli',
    ],
  },
  {
    id: 31,
    name: 'Cart - Redux',
    info: 'This app implements basic cart functionality using redux.',
    level: 'advanced',
    img: 'https://d33wubrfki0l68.cloudfront.net/614a7fcecfc27f1e6a93649a/screenshot_2021-09-22-01-00-09-0000.png',
    github_url: 'https://github.com/Ahmed-AlSharkawy/32-cart-react-redux',
    netlify_url: 'https://cart-react-redux-app.netlify.app',
    teqs: ['react', 'redux'],
  },
]

export default AppData
